package com.zgsbrgr.demo.fiba.network.fake

import com.zgsbrgr.demo.fiba.data.MatchDto
import com.zgsbrgr.demo.fiba.data.RosterDto
import com.zgsbrgr.demo.fiba.data.SectionDto
import com.zgsbrgr.demo.fiba.data.TeamDto
import org.intellij.lang.annotations.Language

object FakeDataSource {

    private val sampleHomeMatchTeam = TeamDto(
        team = "Spain",
        id = "03e4a543-4147-4818-9b4e-9ffe89f7d2b2",
        points = 114,
        winner = true
    )

    private val sampleAwayMatchTeam = TeamDto(
        team = "Bulgaria",
        id = "2483741e-3f32-4d2f-8e77-fbaa08f5636c",
        points = 87,
        winner = false
    )

    private val sampleMatch = MatchDto(
        date = "2022-09-01",
        tag = "FIBA EuroBasket",
        thumb = "https://dev.zgsbrgr.com/fiba/img/day1/1.webp",
        home = sampleHomeMatchTeam,
        away = sampleAwayMatchTeam
    )

    val sampleSection = SectionDto(
        section = "Game Day 1",
        matches = listOf(sampleMatch)
    )

    val sampleRoster = RosterDto(
        player = "Mateusz Ponitka",
        pos = "SG",
        height = "1m98",
        age = 29,
        pts = 13.4,
        reb = 5.3,
        ast = 5.7,
        gp = 9,
        winLose = "5-4",
        min = 27.1,
        twoPercent = "51%",
        threePercent = "30.8%",
        fieldGoalPercent = "42.2%",
        freeThrowPercent = "75%",
        offReb = 0.8,
        reb1 = 5.3,
        ast1 = 5.7,
        steal = 1.6,
        to = 2.8,
        block = 0.2,
        fo = 2.1,
        pts1 = 13.4,
        eff = 16.4
    )

    @Language("JSON")
    val sectionData = """
[
  {
			"section": "Game Day 1",
			"matches": [{
					"date": "2022-09-01",
					"tag": "FIBA EuroBasket",
					"thumb": "https://dev.zgsbrgr.com/fiba/img/day1/1.webp",
					"home": {
						"team": "Spain",
						"id":"03e4a543-4147-4818-9b4e-9ffe89f7d2b2",
						"points": 114,
						"winner": true
					},
					"away": {
						"team": "Bulgaria",
						"id": "2483741e-3f32-4d2f-8e77-fbaa08f5636c",
						"points": 87,
						"winner": false
					}
				}
				
			]
		}
]       
    """.trimIndent()

    @Language("JSON")
    val rosterData = """
[
    {
        "Player": "Mateusz Ponitka",
        "Pos.": "SG",
        "Height": "1m98",
        "Age": 29,
        "Pts": 13.4,
        "Reb": 5.3,
        "Ast": 5.7,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 27.1,
        "2P%": "51%",
        "3P%": "30.8%",
        "FG%": "42.2%",
        "FT%": "75%",
        "Or": 0.8,
        "Reb__1": 5.3,
        "Ast__1": 5.7,
        "Stl": 1.6,
        "To": 2.8,
        "Blk": 0.2,
        "Fo": 2.1,
        "Pts__1": 13.4,
        "Eff": 16.4
      },
      {
        "Player": "A.J. Slaughter",
        "Pos.": "PG",
        "Height": "1m91",
        "Age": 35,
        "Pts": 13.2,
        "Reb": 2.1,
        "Ast": 3.8,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 27.1,
        "2P%": "48.7%",
        "3P%": "36.9%",
        "FG%": "41.3%",
        "FT%": "75%",
        "Or": 0.1,
        "Reb__1": 2.1,
        "Ast__1": 3.8,
        "Stl": 1.3,
        "To": 1.1,
        "Blk": 0.1,
        "Fo": 1.4,
        "Pts__1": 13.2,
        "Eff": 12.3
      },
      {
        "Player": "Michal Sokolowski",
        "Pos.": "SG",
        "Height": "1m96",
        "Age": 30,
        "Pts": 12.2,
        "Reb": 4.3,
        "Ast": 2.2,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 30.4,
        "2P%": "62.2%",
        "3P%": "36.8%",
        "FG%": "49.3%",
        "FT%": "64.7%",
        "Or": 1.1,
        "Reb__1": 4.3,
        "Ast__1": 2.2,
        "Stl": 1,
        "To": 1.3,
        "Blk": 0,
        "Fo": 2.2,
        "Pts__1": 12.2,
        "Eff": 12.9
      },
      {
        "Player": "Aleksander Balcerowski",
        "Pos.": "C",
        "Height": "2m19",
        "Age": 22,
        "Pts": 10.3,
        "Reb": 3.9,
        "Ast": 2.1,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 21.7,
        "2P%": "68.6%",
        "3P%": "26.3%",
        "FG%": "57.1%",
        "FT%": "57.1%",
        "Or": 1.4,
        "Reb__1": 3.9,
        "Ast__1": 2.1,
        "Stl": 0.4,
        "To": 2.2,
        "Blk": 0.8,
        "Fo": 3.2,
        "Pts__1": 10.3,
        "Eff": 11.3
      },
      {
        "Player": "Michal Michalak",
        "Pos.": "SG",
        "Height": "1m97",
        "Age": 29,
        "Pts": 6,
        "Reb": 2.8,
        "Ast": 0.9,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 14.9,
        "2P%": "46.4%",
        "3P%": "35.3%",
        "FG%": "42.2%",
        "FT%": "62.5%",
        "Or": 0.7,
        "Reb__1": 2.8,
        "Ast__1": 0.9,
        "Stl": 0.3,
        "To": 0.6,
        "Blk": 0,
        "Fo": 1.3,
        "Pts__1": 6,
        "Eff": 5.9
      },
      {
        "Player": "Aaron Cel",
        "Pos.": "PF",
        "Height": "2m03",
        "Age": 35,
        "Pts": 5,
        "Reb": 3.1,
        "Ast": 1.6,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 19.6,
        "2P%": "52.4%",
        "3P%": "28.6%",
        "FG%": "40.5%",
        "FT%": "100%",
        "Or": 0.1,
        "Reb__1": 3.1,
        "Ast__1": 1.6,
        "Stl": 0.7,
        "To": 0.7,
        "Blk": 0.1,
        "Fo": 1.9,
        "Pts__1": 5,
        "Eff": 7
      },
      {
        "Player": "Jakub Garbacz",
        "Pos.": "SF",
        "Height": "1m97",
        "Age": 28,
        "Pts": 4.8,
        "Reb": 1.2,
        "Ast": 0.1,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 11.6,
        "2P%": "100%",
        "3P%": "47.8%",
        "FG%": "52%",
        "FT%": "75%",
        "Or": 0.1,
        "Reb__1": 1.2,
        "Ast__1": 0.1,
        "Stl": 0.1,
        "To": 0.2,
        "Blk": 0,
        "Fo": 1.1,
        "Pts__1": 4.8,
        "Eff": 4.4
      },
      {
        "Player": "Jaroslaw Zyskowski",
        "Pos.": "SG",
        "Height": "2m03",
        "Age": 30,
        "Pts": 4.3,
        "Reb": 1.4,
        "Ast": 0.7,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 18.1,
        "2P%": "29.6%",
        "3P%": "23.5%",
        "FG%": "27.3%",
        "FT%": "73.3%",
        "Or": 0.3,
        "Reb__1": 1.4,
        "Ast__1": 0.7,
        "Stl": 0.2,
        "To": 0.4,
        "Blk": 0,
        "Fo": 1.7,
        "Pts__1": 4.3,
        "Eff": 2.2
      },
      {
        "Player": "Aleksander Dziewa",
        "Pos.": "C",
        "Height": "2m05",
        "Age": 25,
        "Pts": 3.4,
        "Reb": 3,
        "Ast": 0.6,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 13.9,
        "2P%": "40%",
        "3P%": "25%",
        "FG%": "37.5%",
        "FT%": "57.1%",
        "Or": 1.3,
        "Reb__1": 3,
        "Ast__1": 0.6,
        "Stl": 0.1,
        "To": 0.3,
        "Blk": 0.2,
        "Fo": 2.2,
        "Pts__1": 3.4,
        "Eff": 4.3
      },
      {
        "Player": "Lukasz Kolenda",
        "Pos.": "PG",
        "Height": "1m95",
        "Age": 23,
        "Pts": 2.8,
        "Reb": 0.8,
        "Ast": 0.7,
        "GP": 6,
        "W-L": "2-4",
        "MIN": 7.2,
        "2P%": "71.4%",
        "3P%": "16.7%",
        "FG%": "46.2%",
        "FT%": "100%",
        "Or": 0.2,
        "Reb__1": 0.8,
        "Ast__1": 0.7,
        "Stl": 0.3,
        "To": 0.7,
        "Blk": 0,
        "Fo": 0.3,
        "Pts__1": 2.8,
        "Eff": 2.8
      },
      {
        "Player": "Jakub Schenk",
        "Pos.": "PG",
        "Height": "1m84",
        "Age": 28,
        "Pts": 1.7,
        "Reb": 0.4,
        "Ast": 1.1,
        "GP": 7,
        "W-L": "4-3",
        "MIN": 6.3,
        "2P%": "50%",
        "3P%": "25%",
        "FG%": "41.7%",
        "FT%": "100%",
        "Or": 0.1,
        "Reb__1": 0.4,
        "Ast__1": 1.1,
        "Stl": 0,
        "To": 0.7,
        "Blk": 0,
        "Fo": 1,
        "Pts__1": 1.7,
        "Eff": 1.6
      },
      {
        "Player": "Dominik Olejniczak",
        "Pos.": "C",
        "Height": "2m13",
        "Age": 26,
        "Pts": 1.4,
        "Reb": 1.4,
        "Ast": 0.3,
        "GP": 7,
        "W-L": "4-3",
        "MIN": 7.3,
        "2P%": "40%",
        "3P%": "-",
        "FG%": "40%",
        "FT%": "75%",
        "Or": 0.4,
        "Reb__1": 1.4,
        "Ast__1": 0.3,
        "Stl": 0.3,
        "To": 1,
        "Blk": 0.3,
        "Fo": 1.6,
        "Pts__1": 1.4,
        "Eff": 2
      },
      {
        "Player": "Total",
        "Pos.": "-",
        "Height": "",
        "Age": null,
        "Pts": 77.1,
        "Reb": 29.2,
        "Ast": 19.1,
        "GP": 9,
        "W-L": "5-4",
        "MIN": 199.7,
        "2P%": "52.7%",
        "3P%": "33.6%",
        "FG%": "43.9%",
        "FT%": "69.8%",
        "Or": 6.6,
        "Reb__1": 29.2,
        "Ast__1": 19.1,
        "Stl": 6.2,
        "To": 11.4,
        "Blk": 1.7,
        "Fo": 19.4,
        "Pts__1": 77.1,
        "Eff": 81.6
      },
      {
        "Player": "Opponents",
        "Pos.": "-",
        "Height": "",
        "Age": null,
        "Pts": 84.9,
        "Reb": 30.1,
        "Ast": 24.6,
        "GP": 9,
        "W-L": "-",
        "MIN": 199.9,
        "2P%": "58.5%",
        "3P%": "40.2%",
        "FG%": "49.3%",
        "FT%": "73.4%",
        "Or": 6.3,
        "Reb__1": 30.1,
        "Ast__1": 24.6,
        "Stl": 5.9,
        "To": 12.1,
        "Blk": 3.6,
        "Fo": 20,
        "Pts__1": 84.9,
        "Eff": 101.4
      },
      {
        "Player": "Gap",
        "Pos.": "-",
        "Height": "",
        "Age": null,
        "Pts": -7.8,
        "Reb": -0.9,
        "Ast": -5.5,
        "GP": 0,
        "W-L": "-",
        "MIN": -0.3,
        "2P%": "-5,8%",
        "3P%": "-6,6%",
        "FG%": "-5,4%",
        "FT%": "-3,6%",
        "Or": 0.3,
        "Reb__1": -0.9,
        "Ast__1": -5.5,
        "Stl": 0.3,
        "To": -0.7,
        "Blk": -1.9,
        "Fo": -0.6,
        "Pts__1": -7.8,
        "Eff": -19.8
      }
]        
    """.trimIndent()

    @Language("JSON")
    val matchTeamData = """
[
  {
      "team": "Spain",
      "id":"03e4a543-4147-4818-9b4e-9ffe89f7d2b2",
      "points": 114,
      "winner": true
  },
  {
      "team": "Bulgaria",
      "id": "2483741e-3f32-4d2f-8e77-fbaa08f5636c",
      "points": 87,
      "winner": false
  }
]
    """.trimIndent()
}
